### ISSUE TITLE
Getting tests to work

### ISSUE THREAD

**Issue by intellix** [nekkon/angular-cli-library#1]
Hey, I didn't quite want to make a PR cause I wasn't sure which direction you wanted to go. But I figured there's 2 options for getting the tests to run:
 - Create 2x tsconfig.spec.json, which point to the correct test.ts file inside each app (Shared won't be tested)
 - Move test.ts back up a directory and have it test specs globally that it can find between apps/shared.

I think moving test.ts back up a directory for covering shared as well is a good idea, but if you get a couple of large apps then I'm guessing you'll want to test the apps individually. But I guess by then we'll actually have a proper solution from the CLI team :)

**Comment by nekkon** [comment]
I will implement both solutions you suggested so that users can pick either one based on what they need. I will do that tomorrow, as I need some rest :). Thanks for your suggestions.

**Comment by nekkon** [comment]
I developed two test.ts files: app1.test.ts and app2.test.ts The url paths in the test.ts files needed to be constants. Errors were thrown otherwise. 

I managed to make e2e tests be dynamic and based on one config file. 

@intellix  as you correctly said until the CLI team develops a proper solution this is a workaround. Cause you can't wait for something like that to happen (takes time), I believe this solution is the closest to how angular-cli currently works. It shouldn't be a headache migrating to whatever solution they come up.
